Connection singleton
planetmint/planetmint pull request #265
Opened 2022-09-22 22:49 UTC by eckelj

A connection singleton got introduced to avoid connection issues and unstables states and connection configurations.

## Checklist

- [X] version number increased
- [X] CHANGELOG.md updated
- [X] unit test added/adjusted

2022-09-24 22:36 UTC, LaurentMontBlanc requested changes
Looks good to me. Can be merged as soon as comments are resolved and abci test are green 👍🏼

2022-09-24 22:36 UTC, LaurentMontBlanc commented on planetmint/backend/schema.py
> +    print(
remove before merging

2022-09-24 22:36 UTC, LaurentMontBlanc commented on tests/tendermint/test_fastquery.py
> +    # conn = connect()
remove comments before merging

2022-09-26 19:17 UTC, eckelj commented on tests/tendermint/test_fastquery.py
> +    # conn = connect()
thx for mentioning. just did so!

2022-10-28 10:18 UTC, LaurentMontBlanc approved these changes
looks good to me, commented on some minor stuff. is mergeable afterwards

2022-10-28 10:18 UTC, LaurentMontBlanc commented on tests/tendermint/test_lib.py
> +
remove unused lines

2022-10-28 10:18 UTC, LaurentMontBlanc commented on tests/web/test_outputs.py
> +
remove unused lines

2022-10-28 10:18 UTC, LaurentMontBlanc commented on tests/web/test_transactions.py
> +# from planetmint.transactions.common.transaction_mode_types import (
remove unused lines

2022-10-28 10:18 UTC, LaurentMontBlanc commented on docs/root/source/connecting/http-samples/index-response.http
> +  "version": "1.2.2"
increase to 1.3.1

2022-10-28 10:18 UTC, LaurentMontBlanc commented on docs/root/source/connecting/http-samples/api-index-response.http
> +  "docs": "https://docs.planetmint.io/projects/server/en/v1.2.2/http-client-server-api.html",
increase to 1.3.1

2022-11-02 08:49 UTC, eckelj commented on docs/root/source/connecting/http-samples/api-index-response.http
> +  "docs": "https://docs.planetmint.io/projects/server/en/v1.2.2/http-client-server-api.html",
thx! done!

2022-11-02 08:49 UTC, eckelj commented on tests/tendermint/test_lib.py
> +
thx! done!

2022-11-02 08:51 UTC, merged